version: '2.1'
services:
  host:
    image: docker.storemy.work/megalan
    build:
      context: .
    network_mode: host
    privileged: true
    command: megalan DEBUG=2 IP="172.20.2.1/24" IP="fd20::1/64" HOST="44.131.14.255 206" RT=10
  node1:
    image: docker.storemy.work/megalan
    networks:
      test:
        ipv4_address: 172.20.1.2
        ipv6_address: fc20::2
    privileged: true
    command: megalan PORT=201 IP="172.20.2.2/24" IP="fd20::2/64" HOST="172.20.1.1 206" RT=10
  node2:
    image: docker.storemy.work/megalan
    networks:
      test:
        ipv4_address: 172.20.1.3
        ipv6_address: fc20::3
    privileged: true
    command: megalan PORT=202 IP="172.20.2.3/24" IP="fd20::3/64" HOST="172.20.1.1 206" RT=10
  node3:
    image: docker.storemy.work/megalan
    networks:
      test:
        ipv4_address: 172.20.1.4
        ipv6_address: fc20::4
    privileged: true
    command: megalan PORT=203 IP="172.20.2.4/24" IP="fd20::4/64" HOST="172.20.1.2 201" RT=10
networks:
  test:
    enable_ipv6: true
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.1.1/24
       - subnet: fc20::1/64
